//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messanger.DataServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services/dataservice/", ConfigurationName="DataServiceRef.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertConsumer", ReplyAction="http://services/dataservice/IDataService/InsertConsumerResponse")]
        void InsertConsumer(DataService.ConsumerContract consumerContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertConsumer", ReplyAction="http://services/dataservice/IDataService/InsertConsumerResponse")]
        System.Threading.Tasks.Task InsertConsumerAsync(DataService.ConsumerContract consumerContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertConsumerContact", ReplyAction="http://services/dataservice/IDataService/InsertConsumerContactResponse")]
        void InsertConsumerContact(string consumerId, DataService.ContactContract contactContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertConsumerContact", ReplyAction="http://services/dataservice/IDataService/InsertConsumerContactResponse")]
        System.Threading.Tasks.Task InsertConsumerContactAsync(string consumerId, DataService.ContactContract contactContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertDialog", ReplyAction="http://services/dataservice/IDataService/InsertDialogResponse")]
        void InsertDialog(DataService.DialogContract dialogContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertDialog", ReplyAction="http://services/dataservice/IDataService/InsertDialogResponse")]
        System.Threading.Tasks.Task InsertDialogAsync(DataService.DialogContract dialogContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertMessages", ReplyAction="http://services/dataservice/IDataService/InsertMessagesResponse")]
        void InsertMessages(DataService.MessageContract[] messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertMessages", ReplyAction="http://services/dataservice/IDataService/InsertMessagesResponse")]
        System.Threading.Tasks.Task InsertMessagesAsync(DataService.MessageContract[] messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertMultimedias", ReplyAction="http://services/dataservice/IDataService/InsertMultimediasResponse")]
        void InsertMultimedias(DataService.MultimediaContract[] multimedias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/InsertMultimedias", ReplyAction="http://services/dataservice/IDataService/InsertMultimediasResponse")]
        System.Threading.Tasks.Task InsertMultimediasAsync(DataService.MultimediaContract[] multimedias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetConsumerContactsById", ReplyAction="http://services/dataservice/IDataService/GetConsumerContactsByIdResponse")]
        DataService.ConsumerContract[] GetConsumerContactsById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetConsumerContactsById", ReplyAction="http://services/dataservice/IDataService/GetConsumerContactsByIdResponse")]
        System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumerContactsByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetConsumerById", ReplyAction="http://services/dataservice/IDataService/GetConsumerByIdResponse")]
        DataService.ConsumerContract GetConsumerById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetConsumerById", ReplyAction="http://services/dataservice/IDataService/GetConsumerByIdResponse")]
        System.Threading.Tasks.Task<DataService.ConsumerContract> GetConsumerByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetConsumersByMatchingNameWithOffsetAndL" +
            "imit", ReplyAction="http://services/dataservice/IDataService/GetConsumersByMatchingNameWithOffsetAndL" +
            "imitResponse")]
        DataService.ConsumerContract[] GetConsumersByMatchingNameWithOffsetAndLimit(string name, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetConsumersByMatchingNameWithOffsetAndL" +
            "imit", ReplyAction="http://services/dataservice/IDataService/GetConsumersByMatchingNameWithOffsetAndL" +
            "imitResponse")]
        System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumersByMatchingNameWithOffsetAndLimitAsync(string name, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetDialogsByConsumerIdWithOffsetAndLimit" +
            "", ReplyAction="http://services/dataservice/IDataService/GetDialogsByConsumerIdWithOffsetAndLimit" +
            "Response")]
        DataService.DialogContract[] GetDialogsByConsumerIdWithOffsetAndLimit(string consumerId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetDialogsByConsumerIdWithOffsetAndLimit" +
            "", ReplyAction="http://services/dataservice/IDataService/GetDialogsByConsumerIdWithOffsetAndLimit" +
            "Response")]
        System.Threading.Tasks.Task<DataService.DialogContract[]> GetDialogsByConsumerIdWithOffsetAndLimitAsync(string consumerId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetMessagesByDialogIdWithOffsetAndLimit", ReplyAction="http://services/dataservice/IDataService/GetMessagesByDialogIdWithOffsetAndLimitR" +
            "esponse")]
        DataService.MessageContract[] GetMessagesByDialogIdWithOffsetAndLimit(int dialogId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetMessagesByDialogIdWithOffsetAndLimit", ReplyAction="http://services/dataservice/IDataService/GetMessagesByDialogIdWithOffsetAndLimitR" +
            "esponse")]
        System.Threading.Tasks.Task<DataService.MessageContract[]> GetMessagesByDialogIdWithOffsetAndLimitAsync(int dialogId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetAttachedMultimediasByMessageId", ReplyAction="http://services/dataservice/IDataService/GetAttachedMultimediasByMessageIdRespons" +
            "e")]
        DataService.MultimediaContract[] GetAttachedMultimediasByMessageId(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetAttachedMultimediasByMessageId", ReplyAction="http://services/dataservice/IDataService/GetAttachedMultimediasByMessageIdRespons" +
            "e")]
        System.Threading.Tasks.Task<DataService.MultimediaContract[]> GetAttachedMultimediasByMessageIdAsync(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetMultimediaById", ReplyAction="http://services/dataservice/IDataService/GetMultimediaByIdResponse")]
        DataService.MultimediaContract GetMultimediaById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services/dataservice/IDataService/GetMultimediaById", ReplyAction="http://services/dataservice/IDataService/GetMultimediaByIdResponse")]
        System.Threading.Tasks.Task<DataService.MultimediaContract> GetMultimediaByIdAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Messanger.DataServiceRef.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Messanger.DataServiceRef.IDataService>, Messanger.DataServiceRef.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertConsumer(DataService.ConsumerContract consumerContract) {
            base.Channel.InsertConsumer(consumerContract);
        }
        
        public System.Threading.Tasks.Task InsertConsumerAsync(DataService.ConsumerContract consumerContract) {
            return base.Channel.InsertConsumerAsync(consumerContract);
        }
        
        public void InsertConsumerContact(string consumerId, DataService.ContactContract contactContract) {
            base.Channel.InsertConsumerContact(consumerId, contactContract);
        }
        
        public System.Threading.Tasks.Task InsertConsumerContactAsync(string consumerId, DataService.ContactContract contactContract) {
            return base.Channel.InsertConsumerContactAsync(consumerId, contactContract);
        }
        
        public void InsertDialog(DataService.DialogContract dialogContract) {
            base.Channel.InsertDialog(dialogContract);
        }
        
        public System.Threading.Tasks.Task InsertDialogAsync(DataService.DialogContract dialogContract) {
            return base.Channel.InsertDialogAsync(dialogContract);
        }
        
        public void InsertMessages(DataService.MessageContract[] messages) {
            base.Channel.InsertMessages(messages);
        }
        
        public System.Threading.Tasks.Task InsertMessagesAsync(DataService.MessageContract[] messages) {
            return base.Channel.InsertMessagesAsync(messages);
        }
        
        public void InsertMultimedias(DataService.MultimediaContract[] multimedias) {
            base.Channel.InsertMultimedias(multimedias);
        }
        
        public System.Threading.Tasks.Task InsertMultimediasAsync(DataService.MultimediaContract[] multimedias) {
            return base.Channel.InsertMultimediasAsync(multimedias);
        }
        
        public DataService.ConsumerContract[] GetConsumerContactsById(string id) {
            return base.Channel.GetConsumerContactsById(id);
        }
        
        public System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumerContactsByIdAsync(string id) {
            return base.Channel.GetConsumerContactsByIdAsync(id);
        }
        
        public DataService.ConsumerContract GetConsumerById(string id) {
            return base.Channel.GetConsumerById(id);
        }
        
        public System.Threading.Tasks.Task<DataService.ConsumerContract> GetConsumerByIdAsync(string id) {
            return base.Channel.GetConsumerByIdAsync(id);
        }
        
        public DataService.ConsumerContract[] GetConsumersByMatchingNameWithOffsetAndLimit(string name, int offset, int limit) {
            return base.Channel.GetConsumersByMatchingNameWithOffsetAndLimit(name, offset, limit);
        }
        
        public System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumersByMatchingNameWithOffsetAndLimitAsync(string name, int offset, int limit) {
            return base.Channel.GetConsumersByMatchingNameWithOffsetAndLimitAsync(name, offset, limit);
        }
        
        public DataService.DialogContract[] GetDialogsByConsumerIdWithOffsetAndLimit(string consumerId, int offset, int limit) {
            return base.Channel.GetDialogsByConsumerIdWithOffsetAndLimit(consumerId, offset, limit);
        }
        
        public System.Threading.Tasks.Task<DataService.DialogContract[]> GetDialogsByConsumerIdWithOffsetAndLimitAsync(string consumerId, int offset, int limit) {
            return base.Channel.GetDialogsByConsumerIdWithOffsetAndLimitAsync(consumerId, offset, limit);
        }
        
        public DataService.MessageContract[] GetMessagesByDialogIdWithOffsetAndLimit(int dialogId, int offset, int limit) {
            return base.Channel.GetMessagesByDialogIdWithOffsetAndLimit(dialogId, offset, limit);
        }
        
        public System.Threading.Tasks.Task<DataService.MessageContract[]> GetMessagesByDialogIdWithOffsetAndLimitAsync(int dialogId, int offset, int limit) {
            return base.Channel.GetMessagesByDialogIdWithOffsetAndLimitAsync(dialogId, offset, limit);
        }
        
        public DataService.MultimediaContract[] GetAttachedMultimediasByMessageId(string messageId) {
            return base.Channel.GetAttachedMultimediasByMessageId(messageId);
        }
        
        public System.Threading.Tasks.Task<DataService.MultimediaContract[]> GetAttachedMultimediasByMessageIdAsync(string messageId) {
            return base.Channel.GetAttachedMultimediasByMessageIdAsync(messageId);
        }
        
        public DataService.MultimediaContract GetMultimediaById(string id) {
            return base.Channel.GetMultimediaById(id);
        }
        
        public System.Threading.Tasks.Task<DataService.MultimediaContract> GetMultimediaByIdAsync(string id) {
            return base.Channel.GetMultimediaByIdAsync(id);
        }
    }
}
