//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messanger.DataServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataServiceRef.IDataService", CallbackContract=typeof(Messanger.DataServiceRef.IDataServiceCallback))]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertConsumer", ReplyAction="http://tempuri.org/IDataService/InsertConsumerResponse")]
        void InsertConsumer(DataService.ConsumerContract consumerContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertConsumer", ReplyAction="http://tempuri.org/IDataService/InsertConsumerResponse")]
        System.Threading.Tasks.Task InsertConsumerAsync(DataService.ConsumerContract consumerContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertConsumerContact", ReplyAction="http://tempuri.org/IDataService/InsertConsumerContactResponse")]
        void InsertConsumerContact(string consumerId, DataService.ContactContract contactContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertConsumerContact", ReplyAction="http://tempuri.org/IDataService/InsertConsumerContactResponse")]
        System.Threading.Tasks.Task InsertConsumerContactAsync(string consumerId, DataService.ContactContract contactContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertDialog", ReplyAction="http://tempuri.org/IDataService/InsertDialogResponse")]
        void InsertDialog(DataService.DialogContract dialogContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertDialog", ReplyAction="http://tempuri.org/IDataService/InsertDialogResponse")]
        System.Threading.Tasks.Task InsertDialogAsync(DataService.DialogContract dialogContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertMessages", ReplyAction="http://tempuri.org/IDataService/InsertMessagesResponse")]
        void InsertMessages(DataService.MessageContract[] messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertMessages", ReplyAction="http://tempuri.org/IDataService/InsertMessagesResponse")]
        System.Threading.Tasks.Task InsertMessagesAsync(DataService.MessageContract[] messages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertMultimedias", ReplyAction="http://tempuri.org/IDataService/InsertMultimediasResponse")]
        void InsertMultimedias(DataService.MultimediaContract[] multimedias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/InsertMultimedias", ReplyAction="http://tempuri.org/IDataService/InsertMultimediasResponse")]
        System.Threading.Tasks.Task InsertMultimediasAsync(DataService.MultimediaContract[] multimedias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConsumerContactsById", ReplyAction="http://tempuri.org/IDataService/GetConsumerContactsByIdResponse")]
        DataService.ConsumerContract[] GetConsumerContactsById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConsumerContactsById", ReplyAction="http://tempuri.org/IDataService/GetConsumerContactsByIdResponse")]
        System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumerContactsByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConsumerDataById", ReplyAction="http://tempuri.org/IDataService/GetConsumerDataByIdResponse")]
        DataService.ConsumerContract GetConsumerDataById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConsumerDataById", ReplyAction="http://tempuri.org/IDataService/GetConsumerDataByIdResponse")]
        System.Threading.Tasks.Task<DataService.ConsumerContract> GetConsumerDataByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConsumersByMatchingNameWithOffsetAndLimit", ReplyAction="http://tempuri.org/IDataService/GetConsumersByMatchingNameWithOffsetAndLimitRespo" +
            "nse")]
        DataService.ConsumerContract[] GetConsumersByMatchingNameWithOffsetAndLimit(string name, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConsumersByMatchingNameWithOffsetAndLimit", ReplyAction="http://tempuri.org/IDataService/GetConsumersByMatchingNameWithOffsetAndLimitRespo" +
            "nse")]
        System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumersByMatchingNameWithOffsetAndLimitAsync(string name, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDialogsByConsumerIdWithOffsetAndLimit", ReplyAction="http://tempuri.org/IDataService/GetDialogsByConsumerIdWithOffsetAndLimitResponse")]
        DataService.DialogContract[] GetDialogsByConsumerIdWithOffsetAndLimit(string consumerId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetDialogsByConsumerIdWithOffsetAndLimit", ReplyAction="http://tempuri.org/IDataService/GetDialogsByConsumerIdWithOffsetAndLimitResponse")]
        System.Threading.Tasks.Task<DataService.DialogContract[]> GetDialogsByConsumerIdWithOffsetAndLimitAsync(string consumerId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetMessagesByDialogIdWithOffsetAndLimit", ReplyAction="http://tempuri.org/IDataService/GetMessagesByDialogIdWithOffsetAndLimitResponse")]
        DataService.MessageContract[] GetMessagesByDialogIdWithOffsetAndLimit(int dialogId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetMessagesByDialogIdWithOffsetAndLimit", ReplyAction="http://tempuri.org/IDataService/GetMessagesByDialogIdWithOffsetAndLimitResponse")]
        System.Threading.Tasks.Task<DataService.MessageContract[]> GetMessagesByDialogIdWithOffsetAndLimitAsync(int dialogId, int offset, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAttachedMultimediasByMessageId", ReplyAction="http://tempuri.org/IDataService/GetAttachedMultimediasByMessageIdResponse")]
        DataService.MultimediaContract[] GetAttachedMultimediasByMessageId(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAttachedMultimediasByMessageId", ReplyAction="http://tempuri.org/IDataService/GetAttachedMultimediasByMessageIdResponse")]
        System.Threading.Tasks.Task<DataService.MultimediaContract[]> GetAttachedMultimediasByMessageIdAsync(string messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetMultimediaById", ReplyAction="http://tempuri.org/IDataService/GetMultimediaByIdResponse")]
        DataService.MultimediaContract GetMultimediaById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetMultimediaById", ReplyAction="http://tempuri.org/IDataService/GetMultimediaByIdResponse")]
        System.Threading.Tasks.Task<DataService.MultimediaContract> GetMultimediaByIdAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataService/OnComplete")]
        void OnComplete();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDataService/OnError")]
        void OnError();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : Messanger.DataServiceRef.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.DuplexClientBase<Messanger.DataServiceRef.IDataService>, Messanger.DataServiceRef.IDataService {
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void InsertConsumer(DataService.ConsumerContract consumerContract) {
            base.Channel.InsertConsumer(consumerContract);
        }
        
        public System.Threading.Tasks.Task InsertConsumerAsync(DataService.ConsumerContract consumerContract) {
            return base.Channel.InsertConsumerAsync(consumerContract);
        }
        
        public void InsertConsumerContact(string consumerId, DataService.ContactContract contactContract) {
            base.Channel.InsertConsumerContact(consumerId, contactContract);
        }
        
        public System.Threading.Tasks.Task InsertConsumerContactAsync(string consumerId, DataService.ContactContract contactContract) {
            return base.Channel.InsertConsumerContactAsync(consumerId, contactContract);
        }
        
        public void InsertDialog(DataService.DialogContract dialogContract) {
            base.Channel.InsertDialog(dialogContract);
        }
        
        public System.Threading.Tasks.Task InsertDialogAsync(DataService.DialogContract dialogContract) {
            return base.Channel.InsertDialogAsync(dialogContract);
        }
        
        public void InsertMessages(DataService.MessageContract[] messages) {
            base.Channel.InsertMessages(messages);
        }
        
        public System.Threading.Tasks.Task InsertMessagesAsync(DataService.MessageContract[] messages) {
            return base.Channel.InsertMessagesAsync(messages);
        }
        
        public void InsertMultimedias(DataService.MultimediaContract[] multimedias) {
            base.Channel.InsertMultimedias(multimedias);
        }
        
        public System.Threading.Tasks.Task InsertMultimediasAsync(DataService.MultimediaContract[] multimedias) {
            return base.Channel.InsertMultimediasAsync(multimedias);
        }
        
        public DataService.ConsumerContract[] GetConsumerContactsById(string id) {
            return base.Channel.GetConsumerContactsById(id);
        }
        
        public System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumerContactsByIdAsync(string id) {
            return base.Channel.GetConsumerContactsByIdAsync(id);
        }
        
        public DataService.ConsumerContract GetConsumerDataById(string id) {
            return base.Channel.GetConsumerDataById(id);
        }
        
        public System.Threading.Tasks.Task<DataService.ConsumerContract> GetConsumerDataByIdAsync(string id) {
            return base.Channel.GetConsumerDataByIdAsync(id);
        }
        
        public DataService.ConsumerContract[] GetConsumersByMatchingNameWithOffsetAndLimit(string name, int offset, int limit) {
            return base.Channel.GetConsumersByMatchingNameWithOffsetAndLimit(name, offset, limit);
        }
        
        public System.Threading.Tasks.Task<DataService.ConsumerContract[]> GetConsumersByMatchingNameWithOffsetAndLimitAsync(string name, int offset, int limit) {
            return base.Channel.GetConsumersByMatchingNameWithOffsetAndLimitAsync(name, offset, limit);
        }
        
        public DataService.DialogContract[] GetDialogsByConsumerIdWithOffsetAndLimit(string consumerId, int offset, int limit) {
            return base.Channel.GetDialogsByConsumerIdWithOffsetAndLimit(consumerId, offset, limit);
        }
        
        public System.Threading.Tasks.Task<DataService.DialogContract[]> GetDialogsByConsumerIdWithOffsetAndLimitAsync(string consumerId, int offset, int limit) {
            return base.Channel.GetDialogsByConsumerIdWithOffsetAndLimitAsync(consumerId, offset, limit);
        }
        
        public DataService.MessageContract[] GetMessagesByDialogIdWithOffsetAndLimit(int dialogId, int offset, int limit) {
            return base.Channel.GetMessagesByDialogIdWithOffsetAndLimit(dialogId, offset, limit);
        }
        
        public System.Threading.Tasks.Task<DataService.MessageContract[]> GetMessagesByDialogIdWithOffsetAndLimitAsync(int dialogId, int offset, int limit) {
            return base.Channel.GetMessagesByDialogIdWithOffsetAndLimitAsync(dialogId, offset, limit);
        }
        
        public DataService.MultimediaContract[] GetAttachedMultimediasByMessageId(string messageId) {
            return base.Channel.GetAttachedMultimediasByMessageId(messageId);
        }
        
        public System.Threading.Tasks.Task<DataService.MultimediaContract[]> GetAttachedMultimediasByMessageIdAsync(string messageId) {
            return base.Channel.GetAttachedMultimediasByMessageIdAsync(messageId);
        }
        
        public DataService.MultimediaContract GetMultimediaById(string id) {
            return base.Channel.GetMultimediaById(id);
        }
        
        public System.Threading.Tasks.Task<DataService.MultimediaContract> GetMultimediaByIdAsync(string id) {
            return base.Channel.GetMultimediaByIdAsync(id);
        }
    }
}
